# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Berry Langerak
tagline:             'Agile solution architect'
description:         'Berry Langerak. Agile solution architect for hire.'
url:                 http://berry-langerak.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Berry Langerak
  url:               https://twitter.com/berry__
  email:             berry.langerak@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
